# -*- coding: utf-8 -*-
"""milestone2_progress.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/spotlur2/Discord-Auto-Mod/blob/bertAndContext/milestone2_progress.ipynb

### Dependencies
"""

#!pip install -q transformers torch

"""### Imports"""

from transformers import pipeline
import pandas as pd
from pprint import pprint

"""### Load toxicity model"""

MODEL_NAME = "unitary/toxic-bert"

classifier = pipeline(
    task="text-classification",
    model=MODEL_NAME,
    tokenizer=MODEL_NAME,
    top_k=None
)

print("Model loaded:", MODEL_NAME)

"""### Helpers"""

def normalize_label(label: str) -> str:
    return label.strip().lower()


def scores_to_dict(model_output):
    """
    Expected output format:
    [[{'label': 'toxic', 'score': 0.99}, ...]]
    """
    if not model_output:
        return {}

    if isinstance(model_output[0], list):
        items = model_output[0]
    else:
        items = model_output

    return {
        normalize_label(item["label"]): float(item["score"])
        for item in items
    }


def predict_message(message: str):
    output = classifier(message)
    return scores_to_dict(output)


def build_context_text(context_messages, current_message, sep=" [SEP] "):
    cleaned_context = [msg.strip() for msg in context_messages if msg and msg.strip()]
    current_message = current_message.strip()

    if cleaned_context:
        return sep.join(cleaned_context + [current_message])
    return current_message


def predict_with_context(context_messages, current_message, sep=" [SEP] "):
    combined_text = build_context_text(context_messages, current_message, sep=sep)
    scores = predict_message(combined_text)
    return {
        "combined_text": combined_text,
        "scores": scores
    }


def get_primary_toxicity_score(scores: dict) -> float:
    return scores.get("toxic", 0.0)


def classify_severity(scores: dict,
                      severe_threshold=0.90,
                      high_threshold=0.75,
                      medium_threshold=0.50):
    toxic_score = get_primary_toxicity_score(scores)

    if toxic_score >= severe_threshold:
        return "severe"
    elif toxic_score >= high_threshold:
        return "high"
    elif toxic_score >= medium_threshold:
        return "medium"
    else:
        return "low"

"""### Baseline test"""

message = "you are trash at this game"

scores = predict_message(message)

print("Message:")
print(message)
print("\nScores:")
pprint(scores)
print("\nSeverity:", classify_severity(scores))

"""### Context aware test"""

context = [
    "you're garbage at this game",
    "i'm not even trying"
]

current_message = "shut up man"

result = predict_with_context(context, current_message)

print("Combined input:")
print(result["combined_text"])
print("\nScores:")
pprint(result["scores"])
print("\nSeverity:", classify_severity(result["scores"]))

"""### With context vs without"""

def compare_no_context_vs_context(context_messages, current_message):
    baseline_scores = predict_message(current_message)
    context_result = predict_with_context(context_messages, current_message)
    context_scores = context_result["scores"]

    comparison = {
        "message": current_message,
        "context": context_messages,
        "baseline_toxic": get_primary_toxicity_score(baseline_scores),
        "context_toxic": get_primary_toxicity_score(context_scores),
        "baseline_scores": baseline_scores,
        "context_scores": context_scores,
        "baseline_severity": classify_severity(baseline_scores),
        "context_severity": classify_severity(context_scores),
        "combined_text": context_result["combined_text"]
    }
    return comparison

example = compare_no_context_vs_context(
    context_messages=[
        "you're so bad lol",
        "nah bro i'm chilling"
    ],
    current_message="idiot"
)

pprint(example)

"""### Demo data"""

demo_data = [
    {
        "context": [],
        "message": "have a nice day",
        "label": "non_toxic"
    },
    {
        "context": [],
        "message": "you are an idiot",
        "label": "toxic"
    },
    {
        "context": ["good game bro", "lmao you sold that round"],
        "message": "you're trash",
        "label": "banter_or_ambiguous"
    },
    {
        "context": ["you're garbage at this game", "i'm not even trying"],
        "message": "shut up man",
        "label": "toxic"
    },
    {
        "context": ["that was actually funny", "nah you're good"],
        "message": "idiot lol",
        "label": "banter_or_ambiguous"
    },
    {
        "context": [],
        "message": "kill yourself",
        "label": "severe_toxic"
    },
    {
        "context": ["check out my stream", "check out my stream", "check out my stream"],
        "message": "check out my stream at mysite.com",
        "label": "spam_or_toxicity_unclear"
    }
]

print(f"Loaded {len(demo_data)} demo examples.")

"""### With context vs without (on demo data)"""

rows = []

for ex in demo_data:
    baseline_scores = predict_message(ex["message"])
    context_result = predict_with_context(ex["context"], ex["message"])
    context_scores = context_result["scores"]

    rows.append({
        "label": ex["label"],
        "message": ex["message"],
        "context": " | ".join(ex["context"]) if ex["context"] else "",
        "baseline_toxic": round(get_primary_toxicity_score(baseline_scores), 4),
        "context_toxic": round(get_primary_toxicity_score(context_scores), 4),
        "baseline_severity": classify_severity(baseline_scores),
        "context_severity": classify_severity(context_scores),
        "baseline_insult": round(baseline_scores.get("insult", 0.0), 4),
        "context_insult": round(context_scores.get("insult", 0.0), 4),
        "baseline_threat": round(baseline_scores.get("threat", 0.0), 4),
        "context_threat": round(context_scores.get("threat", 0.0), 4),
    })

results_df = pd.DataFrame(rows)
results_df

"""### Sort by toxicity score change"""

results_df["toxic_diff"] = (results_df["context_toxic"] - results_df["baseline_toxic"]).abs()
results_df.sort_values("toxic_diff", ascending=False).reset_index(drop=True)

"""### Testing different context window sizes"""

def predict_with_k_context(all_previous_messages, current_message, k, sep=" [SEP] "):
    context_subset = all_previous_messages[-k:] if k > 0 else []
    return predict_with_context(context_subset, current_message, sep=sep)


sample_history = [
    "bro you sold",
    "nah i was lagging",
    "sure lol",
    "you always say that",
    "whatever man"
]

current_message = "idiot"

for k in [0, 1, 3, 5]:
    if k == 0:
        scores = predict_message(current_message)
        combined_text = current_message
    else:
        out = predict_with_k_context(sample_history, current_message, k)
        scores = out["scores"]
        combined_text = out["combined_text"]

    print("=" * 80)
    print(f"k = {k}")
    print("Input:")
    print(combined_text)
    print("toxic score:", round(get_primary_toxicity_score(scores), 4))
    print("severity:", classify_severity(scores))